width: "7in"
color: "white"
color_alt: "#303030"
color_accent: blue
name: "NoMoreNotes::Blog"
pfpsize: 32px
color_link: gray;
color_link_hover: lightgray;
permalink: "/post/:slug"
card_color: "#454545"

defaults:
  -
    scope:
      path: ""
    values:
      layout: blogpost
      appcache: /my.appcache
