width: "5in"
color: "white"
color_alt: "#303030"
color_accent: blue
name: "NoMoreNotes::Blog"
pfpsize: 32px
color_link: gray;
color_link_hover: light-gray;

defaults:
  -
    scope:
      path: ""
    values:
      layout: blogpost
